### ISSUE TITLE
vendor/project (x.x.x) latest is dev-master

### ISSUE THREAD

**Issue by marktopper** [Soullivaneuh/composer-versions-check#49] opened 2017-06-16 07:53 UTC
It keeps saying that `dev-master` is the latest version.

```
86 packages are not up to date:

  - vlucas/phpdotenv (2.4.x-dev) latest is dev-master

  - symfony/css-selector (3.4.x-dev) latest is dev-master

  - tijsverkoyen/css-to-inline-styles (2.2.0) latest is dev-master

  - symfony/polyfill-mbstring (1.5.x-dev) latest is dev-master

  - symfony/var-dumper (3.4.x-dev) latest is dev-master

  - symfony/routing (3.4.x-dev) latest is dev-master

  - symfony/process (3.4.x-dev) latest is dev-master

  - psr/log (1.0.x-dev) latest is dev-master

  - symfony/debug (3.4.x-dev) latest is dev-master

  - symfony/http-foundation (3.4.x-dev) latest is dev-master

  - symfony/event-dispatcher (2.8.x-dev) latest is dev-master

  - symfony/http-kernel (3.4.x-dev) latest is dev-master

  - symfony/finder (3.4.x-dev) latest is dev-master

  - symfony/console (3.4.x-dev) latest is dev-master

  - doctrine/lexer (1.0.x-dev) latest is dev-master

  - egulias/email-validator (2.1.2) latest is dev-master

  - swiftmailer/swiftmailer (6.0.x-dev) latest is dev-master

  - paragonie/random_compat (v2.0.10) latest is dev-master

  - ramsey/uuid (3.x-dev) latest is dev-master

  - symfony/translation (3.4.x-dev) latest is dev-master

  - nesbot/carbon (1.23.x-dev) latest is dev-master

  - mtdowling/cron-expression (v1.2.0) latest is dev-master

  - monolog/monolog (1.x-dev) latest is dev-master

  - league/flysystem (1.0.40) latest is dev-master

  - filp/whoops (2.1.9) latest is dev-master

  - symfony/yaml (3.4.x-dev) latest is dev-master

  - sebastian/diff (1.4.x-dev) latest is dev-master

  - doctrine/instantiator (1.0.x-dev) latest is dev-master

  - phpunit/php-text-template (1.2.1) latest is dev-master

  - phpunit/php-timer (1.0.x-dev) latest is dev-master

  - phpunit/php-file-iterator (1.4.x-dev) latest is dev-master

  - sebastian/recursion-context (3.0.x-dev) latest is dev-master

  - sebastian/exporter (3.1.x-dev) latest is dev-master

  - sebastian/comparator (2.0.x-dev) latest is dev-master

  - webmozart/assert (1.3.x-dev) latest is dev-master

  - phpdocumentor/reflection-common (1.0.x-dev) latest is dev-master

  - phpdocumentor/type-resolver (0.2.1) latest is dev-master

  - phpdocumentor/reflection-docblock (3.1.1) latest is dev-master

  - phpspec/prophecy (1.7.x-dev) latest is dev-master

  - erusev/parsedown (1.6.2) latest is dev-master

  - doctrine/inflector (1.2.x-dev) latest is dev-master

  - laravel/framework (5.5.x-dev) latest is dev-master

  - orchestra/database (3.5.x-dev) latest is dev-master

  - symfony/dom-crawler (3.4.x-dev) latest is dev-master

  - laravel/browser-kit-testing (2.0.x-dev) latest is dev-master

  - sebastian/version (2.0.x-dev) latest is dev-master

  - sebastian/resource-operations (1.0.x-dev) latest is dev-master

  - sebastian/object-reflector (1.1.x-dev) latest is dev-master

  - sebastian/object-enumerator (3.0.x-dev) latest is dev-master

  - sebastian/global-state (2.0.x-dev) latest is dev-master

  - sebastian/environment (3.1.x-dev) latest is dev-master

  - phpunit/phpunit-mock-objects (4.0.x-dev) latest is dev-master

  - theseer/tokenizer (1.1.0) latest is dev-master

  - sebastian/code-unit-reverse-lookup (1.0.x-dev) latest is dev-master

  - phpunit/php-token-stream (2.0.x-dev) latest is dev-master

  - phpunit/php-code-coverage (5.2.x-dev) latest is dev-master

  - phar-io/version (1.0.1) latest is dev-master

  - phar-io/manifest (1.0.x-dev) latest is dev-master

  - myclabs/deep-copy (1.x-dev) latest is dev-master

  - phpunit/phpunit (6.3.x-dev) latest is dev-master

  - fzaninotto/faker (1.6.x-dev) latest is dev-master

  - orchestra/testbench-core (3.5.x-dev) latest is dev-master

  - orchestra/testbench (3.5.x-dev) latest is dev-master

  - orchestra/testbench-browser-kit (3.5.x-dev) latest is dev-master

  - composer/ca-bundle (1.x-dev) latest is dev-master

  - padraic/humbug_get_contents (1.1.0) latest is dev-master

  - padraic/phar-updater (1.0.x-dev) latest is dev-master

  - symfony/stopwatch (3.4.x-dev) latest is dev-master

  - symfony/filesystem (4.0.x-dev) latest is dev-master

  - symfony/config (3.4.x-dev) latest is dev-master

  - guzzle/guzzle (3.9.x-dev) latest is dev-master

  - satooshi/php-coveralls (1.0.x-dev) latest is dev-master

  - codeclimate/php-test-reporter (0.3.x-dev) latest is dev-master

  - doctrine/collections (v1.4.0) latest is dev-master

  - doctrine/cache (1.7.x-dev) latest is dev-master

  - doctrine/annotations (1.4.x-dev) latest is dev-master

  - doctrine/common (2.8.x-dev) latest is dev-master

  - doctrine/dbal (2.6.x-dev) latest is dev-master

  - larapack/doctrine-support (v0.1.2) latest is dev-master

  - psr/http-message (1.0.x-dev) latest is dev-master

  - guzzlehttp/psr7 (1.4.x-dev) latest is dev-master

  - intervention/image (2.3.x-dev) latest is dev-master

  - arrilot/laravel-widgets (3.7.2) latest is dev-master

  - theseer/fdomdocument (1.6.5) latest is dev-master

  - sebastian/finder-facade (1.2.1) latest is dev-master

  - phpunit/phpcov (4.0.x-dev) latest is dev-master
```

**Comment by Soullivaneuh** [comment] 2017-06-16 08:16
Could you please provide?

* `composer --version` command result
* The used version of this plugin (Please try with the last one)
* Your `composer.json` file content?

**Comment by Soullivaneuh** [comment] 2017-06-16 08:17
Duplicate of #46

**Closed by Soullivaneuh** 2017-06-16 08:17 UTC
Labels: bug
