### ISSUE TITLE
Redeclared class error on local install

### ISSUE THREAD

**Issue by OskarStark** [Soullivaneuh/composer-versions-check#9] opened 2015-10-06 07:52 UTC
```bash
oskar.stark:/Volumes/development/workspaces/tvthek/orf (develop)$ composer require sllh/composer-versions-check
Using version ^1.0 for sllh/composer-versions-check
./composer.json has been updated
PHP Fatal error:  Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 17
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/composer:0
PHP   2. require() /usr/local/bin/composer:25
PHP   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   9. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP  10. Composer\Command\Command->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:138
PHP  11. Composer\Console\Application->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
PHP  12. Composer\Factory::create() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:222
PHP  13. Composer\Factory->createComposer() phar:///usr/local/bin/composer/src/Composer/Factory.php:490
PHP  14. Composer\Plugin\PluginManager->loadInstalledPlugins() phar:///usr/local/bin/composer/src/Composer/Factory.php:296
PHP  15. Composer\Plugin\PluginManager->loadRepository() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:71
PHP  16. Composer\Plugin\PluginManager->registerPackage() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:141
PHP  17. eval() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:246

Fatal error: Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 17

Call Stack:
    0.0005     232808   1. {main}() /usr/local/bin/composer:0
    0.0044     419056   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:25
    0.0206    3618472   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
    0.0227    3964624   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
    0.0233    4097328   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0251    4228328   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
    0.0252    4228768   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0252    4229240   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0255    4234872   9. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    2.7486   54634544  10. Composer\Command\Command->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:138
    2.7486   54634640  11. Composer\Console\Application->getComposer() phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
    2.7486   54634688  12. Composer\Factory::create() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:222
    2.7486   54634784  13. Composer\Factory->createComposer() phar:///usr/local/bin/composer/src/Composer/Factory.php:490
    2.8058   54809472  14. Composer\Plugin\PluginManager->loadInstalledPlugins() phar:///usr/local/bin/composer/src/Composer/Factory.php:296
    2.8977   56979616  15. Composer\Plugin\PluginManager->loadRepository() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:71
    2.9030   57219648  16. Composer\Plugin\PluginManager->registerPackage() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:141
    2.9051   57413672  17. eval('?><?php

namespace SLLH\ComposerVersionsCheck;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Package\RootPackageInterface;
use Composer\Plugin\PluginInterface;
use Composer\Repository\RepositoryManager;
use Composer\Script\Event;
use Composer\Script\ScriptEvents;

/**
 * @author Sullivan Senechal <soullivaneuh@gmail.com>
 */
final class VersionsCheckPlugin implements PluginInterface, EventSubscriberInterface
{
    /**
     * @var Composer
     */
    private $composer;

    /**
     * @var IOInterface
     */
    private $io;

    /**
     * @var VersionsCheck
     */
    private $versionsCheck;

    /**
     * {@inheritdoc}
     */
    public function activate(Composer $composer, IOInterface $io)
    {
        $this->composer = $composer;
        $this->io = $io;
        $this->versionsCheck = new VersionsCheck();
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return array(
            ScriptEvents::POST_UPDATE_CMD => array(
                array('postUpdate', -100),
            ),
        );
    }

    /**
     * @param Event $event
     */
    public function postUpdate(Event $event)
    {
        $this->checkVersions($this->composer->getRepositoryManager(), $this->composer->getPackage());
    }

    /**
     * @param RepositoryManager    $repositoryManager
     * @param RootPackageInterface $rootPackage
     */
    private function checkVersions(RepositoryManager $repositoryManager, RootPackageInterface $rootPackage)
    {
        foreach ($repositoryManager->getRepositories() as $repository) {
            $this->versionsCheck->checkPackages(
                $repository,
                $repositoryManager->getLocalRepository(),
                $rootPackage
            );
        }

        $this->io->write($this->versionsCheck->getOutput(), false);
    }
}
') phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:246

oskar.stark:/Volumes/development/workspaces/tvthek/orf (develop)$
```

**Comment by Soullivaneuh** [comment] 2015-10-06 08:00
I assume you have both local and global install in this case?

**Comment by OskarStark** [comment] 2015-10-06 08:00
how can i verify this?

**Comment by Soullivaneuh** [comment] 2015-10-06 08:06
```bash
composer global info -i | grep composer-versions-check
composer info -i | grep composer-versions-check # On the working project directory
```

**Comment by Soullivaneuh** [comment] 2015-10-06 10:07
Ok so the error can be reproduced only when you use the require command with global package already installed:

```bash
sullivan@sweetnexy:~/projects/my/dummy$ cat composer.json
{
    "name": "my/dummy",
    "require": {
        "symfony/symfony": "2.3.*"
    }
}
sullivan@sweetnexy:~/projects/my/dummy$ composer require sllh/composer-versions-check
Using version ^1.0 for sllh/composer-versions-check
./composer.json has been updated
PHP Fatal error:  Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 17
```

But if you add it manually and run an update, the plugin will be installed and executed without any error.

It's a very weird use case. I could add a `class_exists` check on plugin declaration, but it's quite ugly IMO and difficult to add related unit test.

@Seldaek @alcohol maybe do you have some clue to give about this? Thanks. :-)

**Comment by alcohol** [comment] 2015-10-06 10:18
I honestly can't tell you what is wrong without investing a significant amount of time debugging this myself. I never use plugins with Composer. And I certainly don't know why anyone would install a plugin both globally and locally. I'm not sure if this is even worth my time to be honest (don't want to be rude, but I don't get paid for all the support I provide :p). Sounds very much like an edge-case.

**Comment by Soullivaneuh** [comment] 2015-10-06 10:55
@alcohol How yes I just asked for an advice, not a huge debug. ;-)

> And I certainly don't know why anyone would install a plugin both globally and locally.

I globally **and** locally agree for that. :+1: 

But, in some case an open-source project can integrate this plugin and if a contributor clone it with an already globally installed plugin, he cans have issues.

**Comment by alcohol** [comment] 2015-10-06 11:00
I don't really know how plugins are loaded, but I imagine composer always loads both global and local plugins since it has to run both. It shouldn't be hard to detect if something is already loaded though. Not sure if that should be done on Composer's end or the plugin. Can have a peek later.

**Comment by alcohol** [comment] 2015-10-06 11:02
Could you give me the output of running the above with `-vvv`?

**Comment by alcohol** [comment] 2015-10-06 11:13
I'm trying to understand the purpose of [this block of code](/composer/composer/blob/5ccaad92c19ac673435dbb2858ae20d14f34950d/src/Composer/Plugin/PluginManager.php#L243-L249), which obviously is going to fail if a class has any "` implements X`" following it.

**Comment by Soullivaneuh** [comment] 2015-10-06 11:16
I think I found a solution, see https://github.com/composer/composer/pull/4482.

**Comment by alcohol** [comment] 2015-10-06 11:16
Wait no, it should ignore all implementations actually.

**Closed** 2015-10-26 08:03 UTC
Labels: bug
